# Generated by Django 5.0.7 on 2024-07-19 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jam_pelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_ke', models.CharField(max_length=200, null=True)),
                ('jam_pelajaran_dari_ke', models.CharField(max_length=200, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Jam Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='Tahun_pelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tahun Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_guru', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=200, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'guru',
            },
        ),
        migrations.CreateModel(
            name='Piket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_piket', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=200, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Piket',
            },
        ),
        migrations.CreateModel(
            name='Setting_gaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.PositiveIntegerField(null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('tahun_pelajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.tahun_pelajaran')),
            ],
            options={
                'verbose_name_plural': 'Setting Gaji',
            },
        ),
        migrations.CreateModel(
            name='Detail_gaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(max_length=200, null=True)),
                ('nominal', models.PositiveIntegerField(null=True)),
                ('guru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.guru')),
                ('jam_pelajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.jam_pelajaran')),
                ('tahun_pelajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.tahun_pelajaran')),
            ],
            options={
                'verbose_name_plural': 'Detail Gaji',
            },
        ),
    ]
